<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ClubSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::statement("INSERT INTO `clubs` (`id`, `name`, `logo`, `country_code`, `created_at`, `updated_at`) VALUES 
            ('1','FC Bayern München','bayern_minhen.png','GER',NULL,'2021-09-03 09:12:31'),
            ('2','Manchester City FC','mun_city.png','ENG',NULL,'2021-09-05 11:29:57'),
            ('3','Liverpool FC','liverpool.png','ENG',NULL,'2021-09-05 11:32:02'),
            ('4','FC Barcelona','barcelona.png','ESP',NULL,'2021-09-03 10:16:53'),
            ('5','Chelsea FC','chelsea.png','ENG',NULL,'2021-09-03 10:33:01'),
            ('6','Real Madrid CF','real_madrid.png','ESP',NULL,'2021-09-05 11:32:42'),
            ('7','Paris Saint-Germain','psg.png','FRA',NULL,'2021-09-05 11:29:44'),
            ('8','Manchester United','manchester_united.png','ENG',NULL,'2021-09-03 10:35:58'),
            ('9','Juventus','juventus.png','ITA',NULL,'2021-09-05 11:34:16'),
            ('10','Club Atlético de Madrid','atletico_madrid.png','ESP',NULL,'2021-09-05 12:35:35'),
            ('11','Sevilla FC','sevila.png','ESP',NULL,'2021-09-03 10:34:55'),
            ('12','Arsenal FC',NULL,'ENG',NULL,NULL),
            ('13','Tottenham Hotspur',NULL,'ENG',NULL,NULL),
            ('14','AS Roma',NULL,'ITA',NULL,NULL),
            ('15','FC Porto','porto.png','POR',NULL,'2021-09-05 12:35:43'),
            ('16','Borussia Dortmund','borusia_dortmund.png','GER',NULL,'2021-09-05 12:36:27'),
            ('17','RB Leipzig','leipzig.png','GER',NULL,'2021-09-05 11:30:09'),
            ('18','FC Shakhtar Donetsk','shakhtar.png','UKR',NULL,'2021-09-05 12:33:41'),
            ('19','AFC Ajax','ajax.png','NED',NULL,'2021-09-05 11:31:26'),
            ('20','Villarreal CF','vilareal.png','ESP',NULL,'2021-09-03 10:33:38'),
            ('21','SSC Napoli','napoli.png','ITA',NULL,'2021-09-03 10:42:37'),
            ('22','Atalanta BC','atalanta.png','ITA',NULL,'2021-09-03 10:34:22'),
            ('23','FC Salzburg','salzburg.png','AUT',NULL,'2021-09-03 10:34:46'),
            ('24','Olympique Lyonnais','lyonn.png','FRA',NULL,'2021-09-03 10:38:41'),
            ('25','FC Internazionale Milano','inter_milan.png','ITA',NULL,'2021-09-05 11:32:54'),
            ('26','SL Benfica','benfica.png','POR',NULL,'2021-09-05 11:27:17'),
            ('27','SS Lazio','lazio.png','ITA',NULL,'2021-09-03 10:45:43'),
            ('28','Sporting Clube de Portugal','sporting.png','POR',NULL,'2021-09-05 11:31:39'),
            ('29','FC Dynamo Kyiv','dinamo_kyiv.png','UKR',NULL,'2021-09-05 11:27:49'),
            ('30','FC Basel 1893',NULL,'SUI',NULL,NULL),
            ('31','FC Zenit','zenit.png','RUS',NULL,'2021-09-03 10:35:07'),
            ('32','SK Slavia Praha',NULL,'CZE',NULL,NULL),
            ('33','GNK Dinamo Zagreb','dinamo_zag.png','CRO',NULL,'2021-09-03 10:46:00'),
            ('34','Valencia CF',NULL,'ESP',NULL,NULL),
            ('35','Bayer 04 Leverkusen','leverkusen.png','GER',NULL,NULL),
            ('36','Club Brugge','club_bruge.png','BEL',NULL,'2021-09-05 11:29:34'),
            ('37','AC Milan','ac_milan.png','ITA',NULL,'2021-09-05 11:31:50'),
            ('38','BSC Young Boys','young_boys.png','SUI',NULL,'2021-09-03 10:35:19'),
            ('39','Beşiktaş JK','besiktas.png','TUR',NULL,'2021-09-05 12:36:43'),
            ('40','Olympiacos FC','olympiacos.png','GRE',NULL,'2021-09-03 10:39:48'),
            ('41','Eintracht Frankfurt','eintraht.png','GER',NULL,'2021-09-03 10:51:15'),
            ('42','PFC CSKA Moskva',NULL,'RUS',NULL,NULL),
            ('43','Rangers FC','rangers.png','SCO',NULL,'2021-09-03 10:40:38'),
            ('44','FK Crvena zvezda','red_star.png','SRB',NULL,NULL),
            ('45','FC Lokomotiv Moskva','lokomotiv_moscow.png','RUS',NULL,'2021-09-03 10:45:34'),
            ('46','SC Braga','braga.png','POR',NULL,NULL),
            ('47','FC Viktoria Plzeň',NULL,'CZE',NULL,NULL),
            ('48','Olympique de Marseille','marseile.png','FRA',NULL,'2021-09-03 10:49:13'),
            ('49','F.C. Copenhagen',NULL,'DEN',NULL,NULL),
            ('50','Celtic FC','celtic.png','SCO',NULL,'2021-09-03 10:47:47'),
            ('51','FC Krasnodar',NULL,'RUS',NULL,NULL),
            ('52','İstanbul Başakşehir',NULL,'TUR',NULL,NULL),
            ('53','PSV Eindhoven','psv.png','NED',NULL,'2021-09-03 10:40:09'),
            ('54','TSG 1899 Hoffenheim',NULL,'GER',NULL,NULL),
            ('55','Malmö FF','malme.png','SWE',NULL,'2021-09-05 11:34:50'),
            ('56','LASK',NULL,'AUT',NULL,NULL),
            ('57','VfL Borussia Mönchengladbach',NULL,'GER',NULL,NULL),
            ('58','FC Astana',NULL,'KAZ',NULL,NULL),
            ('59','AEK Athens FC',NULL,'GRE',NULL,NULL),
            ('60','PFC Ludogorets 1945','ludogorets.png','BUL',NULL,NULL),
            ('61','Molde FK',NULL,'NOR',NULL,NULL),
            ('62','Stade Rennais FC',NULL,'FRA',NULL,NULL),
            ('63','VfL Wolfsburg','wolfsburg.png','GER',NULL,'2021-09-03 10:35:48'),
            ('64','APOEL FC',NULL,'CYP',NULL,NULL),
            ('65','Leicester City FC','leicester.png','ENG',NULL,'2021-09-03 10:42:50'),
            ('66','West Ham United FC','west_ham.png','ENG',NULL,'2021-09-03 10:47:26'),
            ('67','Wolverhampton Wanderers FC',NULL,'ENG',NULL,NULL),
            ('68','Burnley FC',NULL,'ENG',NULL,NULL),
            ('69','Everton FC',NULL,'ENG',NULL,NULL),
            ('70','FCSB',NULL,'ROU',NULL,NULL),
            ('71','FC BATE Borisov',NULL,'BLR',NULL,NULL),
            ('72','FK Partizan',NULL,'SRB',NULL,NULL),
            ('73','FC Spartak Moskva','sp_moscow.png','RUS',NULL,NULL),
            ('74','LOSC Lille','lille.png','FRA',NULL,'2021-09-05 12:34:47'),
            ('75','Real Sociedad de Fútbol','real_cociedad.png','ESP',NULL,'2021-09-03 10:38:54'),
            ('76','Galatasaray AŞ','galatasaray.png','TUR',NULL,'2021-09-03 10:50:09'),
            ('77','FC Schalke 04',NULL,'GER',NULL,NULL),
            ('78','CFR 1907 Cluj',NULL,'ROU',NULL,NULL),
            ('79','KAA Gent',NULL,'BEL',NULL,NULL),
            ('80','Real Betis Balompié','betis.png','ESP',NULL,'2021-09-03 10:50:24'),
            ('81','Granada CF',NULL,'ESP',NULL,NULL),
            ('82','Getafe CF',NULL,'ESP',NULL,NULL),
            ('83','RCD Espanyol',NULL,'ESP',NULL,NULL),
            ('84','Athletic Club',NULL,'ESP',NULL,NULL),
            ('85','Feyenoord',NULL,'NED',NULL,NULL),
            ('86','Qarabağ FK',NULL,'AZE',NULL,NULL),
            ('87','R. Standard de Liège',NULL,'BEL',NULL,NULL),
            ('88','Maccabi Tel-Aviv FC',NULL,'ISR',NULL,NULL),
            ('89','AZ Alkmaar',NULL,'NED',NULL,NULL),
            ('90','Apollon Limassol FC',NULL,'CYP',NULL,NULL),
            ('91','NK Maribor',NULL,'SVN',NULL,NULL),
            ('92','KRC Genk','genk.png','BEL',NULL,'2021-09-03 10:46:09'),
            ('93','FC Sheriff Tiraspol','sheriff.png','MDA',NULL,'2021-09-05 12:34:01'),
            ('94','FC Zorya Luhansk',NULL,'UKR',NULL,NULL),
            ('95','Torino FC',NULL,'ITA',NULL,NULL),
            ('96','Ferencvárosi TC','ferencvaros.png','HUN',NULL,NULL),
            ('97','HNK Rijeka',NULL,'CRO',NULL,NULL),
            ('98','Rosenborg BK',NULL,'NOR',NULL,NULL),
            ('99','1. FC Union Berlin',NULL,'GER',NULL,NULL),
            ('100','Hertha BSC Berlin',NULL,'GER',NULL,NULL),
            ('101','1. FC Köln',NULL,'GER',NULL,NULL),
            ('102','SC Freiburg',NULL,'GER',NULL,NULL),
            ('103','FC Midtjylland','midtjilend.png','DEN',NULL,NULL),
            ('104','PAOK FC',NULL,'GRE',NULL,NULL),
            ('105','SK Rapid Wien','rapid_wien.png','AUT',NULL,'2021-09-03 10:47:35'),
            ('106','Fehérvár FC',NULL,'HUN',NULL,NULL),
            ('107','Hapoel Beer-Sheva FC',NULL,'ISR',NULL,NULL),
            ('108','AS Monaco FC','monaco.png','FRA',NULL,'2021-09-03 10:48:47'),
            ('109','Wolfsberger AC',NULL,'AUT',NULL,NULL),
            ('110','Royal Antwerp FC','antwerpen.png','BEL',NULL,'2021-09-03 10:39:06'),
            ('111','FK Sūduva',NULL,'LTU',NULL,NULL),
            ('112','Östersunds FK',NULL,'SWE',NULL,NULL),
            ('113','Dundalk FC',NULL,'IRL',NULL,NULL),
            ('114','Fenerbahçe SK','fenerbahce.png','TUR',NULL,'2021-09-03 10:51:25'),
            ('115','KF Shkëndija',NULL,'MKD',NULL,NULL),
            ('116','RSC Anderlecht',NULL,'BEL',NULL,NULL),
            ('117','OGC Nice',NULL,'FRA',NULL,NULL),
            ('118','FC Lugano',NULL,'SUI',NULL,NULL),
            ('119','FC Paços de Ferreira',NULL,'POR',NULL,NULL),
            ('120','CD Santa Clara',NULL,'POR',NULL,NULL),
            ('121','Rio Ave FC',NULL,'POR',NULL,NULL),
            ('122','Vitória SC',NULL,'POR',NULL,NULL),
            ('123','CS Marítimo',NULL,'POR',NULL,NULL),
            ('124','Stade de Reims',NULL,'FRA',NULL,NULL),
            ('125','AS Saint-Étienne',NULL,'FRA',NULL,NULL),
            ('126','Racing Club de Strasbourg Alsace',NULL,'FRA',NULL,NULL),
            ('127','FC Girondins de Bordeaux',NULL,'FRA',NULL,NULL),
            ('128','The New Saints FC',NULL,'WAL',NULL,NULL),
            ('129','FC Spartak Trnava',NULL,'SVK',NULL,NULL),
            ('130','F91 Diddeleng',NULL,'LUX',NULL,NULL),
            ('131','AC Sparta Praha','sparta_praha.png','CZE',NULL,'2021-09-03 10:41:40'),
            ('132','Legia Warszawa','legia_warsaw.png','POL',NULL,NULL),
            ('133','NK Osijek',NULL,'CRO',NULL,NULL),
            ('134','HNK Hajduk Split',NULL,'CRO',NULL,NULL),
            ('135','PFC CSKA-Sofia',NULL,'BUL',NULL,NULL),
            ('136','NK Olimpija Ljubljana',NULL,'SVN',NULL,NULL),
            ('137','Universitatea Craiova',NULL,'ROU',NULL,NULL),
            ('138','FK Austria Wien',NULL,'AUT',NULL,NULL),
            ('139','AEK Larnaca FC',NULL,'CYP',NULL,NULL),
            ('140','FK Sarajevo',NULL,'BIH',NULL,NULL),
            ('141','Linfield FC',NULL,'NIR',NULL,NULL),
            ('142','FK Budućnost Podgorica',NULL,'MNE',NULL,NULL),
            ('143','ŠK Slovan Bratislava',NULL,'SVK',NULL,NULL),
            ('144','FK Jablonec',NULL,'CZE',NULL,NULL),
            ('145','HŠK Zrinjski',NULL,'BIH',NULL,NULL),
            ('146','FC Zürich',NULL,'SUI',NULL,NULL),
            ('147','Vitesse',NULL,'NED',NULL,NULL),
            ('148','Willem II',NULL,'NED',NULL,NULL),
            ('149','FC Utrecht',NULL,'NED',NULL,NULL),
            ('150','FC Luzern',NULL,'SUI',NULL,NULL),
            ('151','NK Domžale',NULL,'SVN',NULL,NULL),
            ('152','FC Dinamo Brest',NULL,'BLR',NULL,NULL),
            ('153','FC Dinamo Tbilisi',NULL,'GEO',NULL,NULL),
            ('154','FC DAC 1904 Dunajská Streda',NULL,'SVK',NULL,NULL),
            ('155','FC Vaduz',NULL,'LIE',NULL,NULL),
            ('156','Aberdeen FC',NULL,'SCO',NULL,NULL),
            ('157','FK Sutjeska',NULL,'MNE',NULL,NULL),
            ('158','FC Shakhtyor Soligorsk',NULL,'BLR',NULL,NULL),
            ('159','KÍ Klaksvík',NULL,'FRO',NULL,NULL),
            ('160','Hibernian FC',NULL,'SCO',NULL,NULL),
            ('161','St Johnstone FC',NULL,'SCO',NULL,NULL),
            ('162','Motherwell FC',NULL,'SCO',NULL,NULL),
            ('163','Kilmarnock FC',NULL,'SCO',NULL,NULL),
            ('164','FC Rubin',NULL,'RUS',NULL,NULL),
            ('165','FC Sochi',NULL,'RUS',NULL,NULL),
            ('166','FC Rostov',NULL,'RUS',NULL,NULL),
            ('167','FC Dynamo Moscow',NULL,'RUS',NULL,NULL),
            ('168','FC Arsenal Tula',NULL,'RUS',NULL,NULL),
            ('169','FC Ufa',NULL,'RUS',NULL,NULL),
            ('170','SK Sturm Graz','sturm_graz.png','AUT',NULL,'2021-09-03 10:48:58'),
            ('171','TSV Hartberg',NULL,'AUT',NULL,NULL),
            ('172','FC Admira Wacker Mödling',NULL,'AUT',NULL,NULL),
            ('173','SCR Altach',NULL,'AUT',NULL,NULL),
            ('174','KF Laçi',NULL,'ALB',NULL,NULL),
            ('175','KKS Lech Poznań',NULL,'POL',NULL,NULL),
            ('176','Kolos Kovalivka',NULL,'UKR',NULL,NULL),
            ('177','FC Vorskla Poltava',NULL,'UKR',NULL,NULL),
            ('178','FC Desna Chernihiv',NULL,'UKR',NULL,NULL),
            ('179','FC Olexandriya',NULL,'UKR',NULL,NULL),
            ('180','FC Mariupol',NULL,'UKR',NULL,NULL),
            ('181','FC Olimpik Donetsk',NULL,'UKR',NULL,NULL),
            ('182','Connah''s Quay Nomads FC',NULL,'WAL',NULL,NULL),
            ('183','FC Flora Tallinn',NULL,'EST',NULL,NULL),
            ('184','PFC Lokomotiv Plovdiv 1926',NULL,'BUL',NULL,NULL),
            ('185','Hibernians FC',NULL,'MLT',NULL,NULL),
            ('186','FH Hafnarfjördur',NULL,'ISL',NULL,NULL),
            ('187','FC Santa Coloma',NULL,'AND',NULL,NULL),
            ('188','Valur',NULL,'ISL',NULL,NULL),
            ('189','Riga FC',NULL,'LVA',NULL,NULL),
            ('190','FC Kairat Almaty',NULL,'KAZ',NULL,NULL),
            ('191','FK Žalgiris Vilnius',NULL,'LTU',NULL,NULL),
            ('192','Alashkert FC',NULL,'ARM',NULL,NULL),
            ('193','Brøndby IF','brondby.png','DEN',NULL,'2021-09-03 10:41:26'),
            ('194','FC Progrès Niederkorn',NULL,'LUX',NULL,NULL),
            ('195','Budapest Honvéd FC',NULL,'HUN',NULL,NULL),
            ('196','FK Kukësi',NULL,'ALB',NULL,NULL),
            ('197','FK Vojvodina',NULL,'SRB',NULL,NULL),
            ('198','FK Čukarički',NULL,'SRB',NULL,NULL),
            ('199','Backa Topola',NULL,'SRB',NULL,NULL),
            ('200','FK Radnicki Niš',NULL,'SRB',NULL,NULL),
            ('201','FK Spartak Subotica',NULL,'SRB',NULL,NULL),
            ('202','FK Mladost Lučani',NULL,'SRB',NULL,NULL),
            ('203','FK Ventspils',NULL,'LVA',NULL,NULL),
            ('204','R. Charleroi SC',NULL,'BEL',NULL,NULL),
            ('205','SV Zulte Waregem',NULL,'BEL',NULL,NULL),
            ('206','KV Oostende',NULL,'BEL',NULL,NULL),
            ('207','Servette FC',NULL,'SUI',NULL,NULL),
            ('208','FC St. Gallen',NULL,'SUI',NULL,NULL),
            ('209','FC Thun',NULL,'SUI',NULL,NULL),
            ('210','FC Sion',NULL,'SUI',NULL,NULL),
            ('211','FC Drita',NULL,'KOS',NULL,NULL),
            ('212','Aris Thessaloniki FC',NULL,'GRE',NULL,NULL),
            ('213','KuPS Kuopio',NULL,'FIN',NULL,NULL),
            ('214','CS Fola Esch',NULL,'LUX',NULL,NULL),
            ('215','FC Slovan Liberec',NULL,'CZE',NULL,NULL),
            ('216','Ararat-Armenia FC',NULL,'ARM',NULL,NULL),
            ('217','FK Riteriai',NULL,'LTU',NULL,NULL),
            ('218','Valletta FC',NULL,'MLT',NULL,NULL),
            ('219','FC Dinamo Minsk',NULL,'BLR',NULL,NULL),
            ('220','AIK',NULL,'SWE',NULL,NULL),
            ('221','Konyaspor',NULL,'TUR',NULL,NULL),
            ('222','NK Lokomotiva Zagreb',NULL,'CRO',NULL,NULL),
            ('223','AEL Limassol FC',NULL,'CYP',NULL,NULL),
            ('224','Omonoia FC',NULL,'CYP',NULL,NULL),
            ('225','Anorthosis Famagusta FC',NULL,'CYP',NULL,NULL),
            ('226','FC Levadia Tallinn',NULL,'EST',NULL,NULL),
            ('227','Lincoln Red Imps FC',NULL,'GIB',NULL,NULL),
            ('228','B36 Tórshavn',NULL,'FRO',NULL,NULL),
            ('229','1. FC Slovácko',NULL,'CZE',NULL,NULL),
            ('230','FK Mladá Boleslav',NULL,'CZE',NULL,NULL),
            ('231','SK Sigma Olomouc',NULL,'CZE',NULL,NULL),
            ('232','FC Zlín',NULL,'CZE',NULL,NULL),
            ('233','Sivasspor',NULL,'TUR',NULL,NULL),
            ('234','Trabzonspor AŞ',NULL,'TUR',NULL,NULL),
            ('235','Alanyaspor',NULL,'TUR',NULL,NULL),
            ('236','Yeni Malatyaspor',NULL,'TUR',NULL,NULL),
            ('237','Akhisar Belediyespor',NULL,'TUR',NULL,NULL),
            ('238','KF Teuta',NULL,'ALB',NULL,NULL),
            ('239','FC Tobol Kostanay',NULL,'KAZ',NULL,NULL),
            ('240','Petrocub-Hincesti',NULL,'MDA',NULL,NULL),
            ('241','FC Shkupi 1927',NULL,'MKD',NULL,NULL),
            ('242','BK Häcken',NULL,'SWE',NULL,NULL),
            ('243','FK Liepāja',NULL,'LVA',NULL,NULL),
            ('244','Europa FC',NULL,'GIB',NULL,NULL),
            ('245','Neftçi PFK',NULL,'AZE',NULL,NULL),
            ('246','Shamrock Rovers FC',NULL,'IRL',NULL,NULL),
            ('247','HJK Helsinki',NULL,'FIN',NULL,NULL),
            ('248','Nõmme Kalju FC',NULL,'EST',NULL,NULL),
            ('249','FC Viitorul',NULL,'ROU',NULL,NULL),
            ('250','Vålerenga Fotball Elite',NULL,'NOR',NULL,NULL),
            ('251','FK Bodø/Glimt',NULL,'NOR',NULL,NULL),
            ('252','Viking FK',NULL,'NOR',NULL,NULL),
            ('253','FK Haugesund',NULL,'NOR',NULL,NULL),
            ('254','SK Brann',NULL,'NOR',NULL,NULL),
            ('255','Sarpsborg 08 FF',NULL,'NOR',NULL,NULL),
            ('256','Lillestrøm SK',NULL,'NOR',NULL,NULL),
            ('257','Odds BK',NULL,'NOR',NULL,NULL),
            ('258','Hammarby Fotboll',NULL,'SWE',NULL,NULL),
            ('259','IF Elfsborg',NULL,'SWE',NULL,NULL),
            ('260','Djurgårdens IF',NULL,'SWE',NULL,NULL),
            ('261','IFK Göteborg',NULL,'SWE',NULL,NULL),
            ('262','IFK Norrköping FK',NULL,'SWE',NULL,NULL),
            ('263','OFI Crete FC',NULL,'GRE',NULL,NULL),
            ('264','Atromitos FC',NULL,'GRE',NULL,NULL),
            ('265','Asteras Tripolis FC',NULL,'GRE',NULL,NULL),
            ('266','Panathinaikos FC',NULL,'GRE',NULL,NULL),
            ('267','Panionios GSS',NULL,'GRE',NULL,NULL),
            ('268','FC Prishtina',NULL,'KOS',NULL,NULL),
            ('269','FK Partizani',NULL,'ALB',NULL,NULL),
            ('270','Stjarnan',NULL,'ISL',NULL,NULL),
            ('271','FC Pyunik',NULL,'ARM',NULL,NULL),
            ('272','AGF Aarhus',NULL,'DEN',NULL,NULL),
            ('273','Randers FC',NULL,'DEN',NULL,NULL),
            ('274','SønderjyskE',NULL,'DEN',NULL,NULL),
            ('275','Esbjerg fB',NULL,'DEN',NULL,NULL),
            ('276','FC Nordsjælland',NULL,'DEN',NULL,NULL),
            ('277','Lyngby BK',NULL,'DEN',NULL,NULL),
            ('278','FC Ashdod',NULL,'ISR',NULL,NULL),
            ('279','Maccabi Haifa FC',NULL,'ISR',NULL,NULL),
            ('280','Beitar Jerusalem FC',NULL,'ISR',NULL,NULL),
            ('281','Bnei Yehuda Tel-Aviv FC',NULL,'ISR',NULL,NULL),
            ('282','Hapoel Haifa FC',NULL,'ISR',NULL,NULL),
            ('283','Breidablik',NULL,'ISL',NULL,NULL),
            ('284','RFS',NULL,'LVA',NULL,NULL),
            ('285','HB Tórshavn',NULL,'FRO',NULL,NULL),
            ('286','Keşla FK',NULL,'AZE',NULL,NULL),
            ('287','Gżira United FC',NULL,'MLT',NULL,NULL),
            ('288','La Fiorita 1967',NULL,'SMR',NULL,NULL),
            ('289','KF Skënderbeu',NULL,'ALB',NULL,NULL),
            ('290','FC Milsami Orhei',NULL,'MDA',NULL,NULL),
            ('291','Coleraine FC',NULL,'NIR',NULL,NULL),
            ('292','NSÍ Runavík',NULL,'FRO',NULL,NULL),
            ('293','FC Torpedo Kutaisi',NULL,'GEO',NULL,NULL),
            ('294','PFC Arda Kardzhali 1924',NULL,'BUL',NULL,NULL),
            ('295','PFC Slavia Sofia',NULL,'BUL',NULL,NULL),
            ('296','PFC Levski Sofia',NULL,'BUL',NULL,NULL),
            ('297','PFC Botev Plovdiv',NULL,'BUL',NULL,NULL),
            ('298','FC Dunav Ruse',NULL,'BUL',NULL,NULL),
            ('299','Újpest FC',NULL,'HUN',NULL,NULL),
            ('300','FK Kauno Žalgiris',NULL,'LTU',NULL,NULL),
            ('301','NK Široki Brijeg',NULL,'BIH',NULL,NULL),
            ('302','Piast Gliwice',NULL,'POL',NULL,NULL),
            ('303','Gabala SC',NULL,'AZE',NULL,NULL),
            ('304','Cork City FC',NULL,'IRL',NULL,NULL),
            ('305','Sepsi Sfantu Gheorghe',NULL,'ROU',NULL,NULL),
            ('306','FC Botoşani',NULL,'ROU',NULL,NULL),
            ('307','FC Dinamo Bucureşti',NULL,'ROU',NULL,NULL),
            ('308','FC Astra Giurgiu',NULL,'GEO',NULL,NULL),
            ('309','FC Dinamo Batumi',NULL,'GEO',NULL,NULL),
            ('310','Bala Town FC',NULL,'WAL',NULL,NULL),
            ('311','SP Tre Penne',NULL,'SMR',NULL,NULL),
            ('312','St Joseph''s FC',NULL,'GIB',NULL,NULL),
            ('313','FC Chikhura Sachkhere',NULL,'GEO',NULL,NULL),
            ('314','Crusaders FC',NULL,'NIR',NULL,NULL),
            ('315','Puskás Akadémia FC',NULL,'HUN',NULL,NULL),
            ('316','Debreceni VSC',NULL,'HUN',NULL,NULL),
            ('317','Vasas FC',NULL,'HUN',NULL,NULL),
            ('318','Bohemian FC',NULL,'IRL',NULL,NULL),
            ('319','FK Borac Banja Luka',NULL,'BIH',NULL,NULL),
            ('320','Inter Club d''Escaldes',NULL,'AND',NULL,NULL),
            ('321','FC Inter Turku',NULL,'FIN',NULL,NULL),
            ('322','FC Urartu',NULL,'ARM',NULL,NULL),
            ('323','NS Mura',NULL,'SVN',NULL,NULL),
            ('324','FC Shakhter Karagandy',NULL,'KAZ',NULL,NULL),
            ('325','KR Reykjavík',NULL,'ISL',NULL,NULL),
            ('326','SP Tre Fiori',NULL,'SMR',NULL,NULL),
            ('327','FC Kaysar Kyzylorda',NULL,'KAZ',NULL,NULL),
            ('328','FC Saburtalo',NULL,'GEO',NULL,NULL),
            ('329','FC Ordabasy Shymkent',NULL,'KAZ',NULL,NULL),
            ('330','MFK Ružomberok',NULL,'SVK',NULL,NULL),
            ('331','FK Željezničar',NULL,'BIH',NULL,NULL),
            ('332','AS Trenčín',NULL,'SVK',NULL,NULL),
            ('333','FK Spartaks Jūrmala',NULL,'LVA',NULL,NULL),
            ('334','FK Vardar',NULL,'MKD',NULL,NULL),
            ('335','FC Irtysh Pavlodar',NULL,'KAZ',NULL,NULL),
            ('336','WKS Śląsk Wrocław',NULL,'POL',NULL,NULL),
            ('337','MKS Pogoń Szczecin',NULL,'POL',NULL,NULL),
            ('338','Raków Czestochowa',NULL,'POL',NULL,NULL),
            ('339','MKS Cracovia Kraków',NULL,'POL',NULL,NULL),
            ('340','KS Lechia Gdańsk',NULL,'POL',NULL,NULL),
            ('341','Jagiellonia Białystok',NULL,'POL',NULL,NULL),
            ('342','Górnik Zabrze',NULL,'POL',NULL,NULL),
            ('343','Arka Gdynia',NULL,'POL',NULL,NULL),
            ('344','Sumqayıt FK',NULL,'AZE',NULL,NULL),
            ('345','NK Celje',NULL,'SVN',NULL,NULL),
            ('346','Sabail',NULL,'AZE',NULL,NULL),
            ('347','NK Rudar Velenje',NULL,'SVN',NULL,NULL),
            ('348','ND Gorica',NULL,'SVN',NULL,NULL),
            ('349','Zirä FK',NULL,'AZE',NULL,NULL),
            ('350','MŠK Žilina',NULL,'SVK',NULL,NULL),
            ('351','KF Tirana',NULL,'ALB',NULL,NULL),
            ('352','Balzan FC',NULL,'MLT',NULL,NULL),
            ('353','FC Honka Espoo',NULL,'FIN',NULL,NULL),
            ('354','FC Torpedo Zhodino',NULL,'BLR',NULL,NULL),
            ('355','FC Sfintul Gheorghe',NULL,'MDA',NULL,NULL),
            ('356','FK Sileks',NULL,'MKD',NULL,NULL),
            ('357','UE Engordany',NULL,'AND',NULL,NULL),
            ('358','OFK Titograd',NULL,'MNE',NULL,NULL),
            ('359','FC Vitebsk',NULL,'BLR',NULL,NULL),
            ('360','Víkingur',NULL,'FRO',NULL,NULL),
            ('361','SS Folgore',NULL,'SMR',NULL,NULL),
            ('362','UE Sant Julià',NULL,'AND',NULL,NULL),
            ('363','Floriana FC',NULL,'MLT',NULL,NULL),
            ('364','FK Zeta',NULL,'MNE',NULL,NULL),
            ('365','Derry City FC',NULL,'IRL',NULL,NULL),
            ('366','Larne FC',NULL,'NIR',NULL,NULL),
            ('367','FK Velež',NULL,'BIH',NULL,NULL),
            ('368','Birkirkara FC',NULL,'MLT',NULL,NULL),
            ('369','Panevezys',NULL,'LTU',NULL,NULL),
            ('370','Glentoran FC',NULL,'NIR',NULL,NULL),
            ('371','FK Valmiera',NULL,'LVA',NULL,NULL),
            ('372','Paide Linnameeskond',NULL,'EST',NULL,NULL),
            ('373','FC Noah',NULL,'ARM',NULL,NULL),
            ('374','Racing FC Union Luxembourg',NULL,'LUX',NULL,NULL),
            ('375','FC Locomotive Tbilisi',NULL,'GEO',NULL,NULL),
            ('376','Ilves Tampere',NULL,'FIN',NULL,NULL),
            ('377','Cliftonville FC',NULL,'NIR',NULL,NULL),
            ('378','JK Narva Trans',NULL,'EST',NULL,NULL),
            ('379','FC Samtredia',NULL,'GEO',NULL,NULL),
            ('380','FC Stumbras',NULL,'LTU',NULL,NULL),
            ('381','FK Atlantas',NULL,'LTU',NULL,NULL),
            ('382','FK Radnik Bijeljina',NULL,'BIH',NULL,NULL),
            ('383','FC Swift Hesper',NULL,'LUX',NULL,NULL),
            ('384','FC Differdange 03',NULL,'LUX',NULL,NULL),
            ('385','Union Titus Petange',NULL,'LUX',NULL,NULL),
            ('386','AS Jeunesse Esch',NULL,'LUX',NULL,NULL),
            ('387','FK Jelgava',NULL,'LVA',NULL,NULL),
            ('388','FC Dinamo-Auto Tiraspol',NULL,'MDA',NULL,NULL),
            ('389','FC Speranța Nisporeni',NULL,'MDA',NULL,NULL),
            ('390','FC Zaria Balti',NULL,'MDA',NULL,NULL),
            ('391','FC Dacia Chisinau',NULL,'MDA',NULL,NULL),
            ('392','KF Llapi 1932',NULL,'KOS',NULL,NULL),
            ('393','KF Gjilani',NULL,'KOS',NULL,NULL),
            ('394','KF Feronikeli',NULL,'KOS',NULL,NULL),
            ('395','KF Trepça’89',NULL,'KOS',NULL,NULL),
            ('396','Sligo Rovers FC',NULL,'IRL',NULL,NULL),
            ('397','Saint Patrick''s Athletic FC',NULL,'IRL',NULL,NULL),
            ('398','Ballymena United FC',NULL,'NIR',NULL,NULL),
            ('399','Glenavon FC',NULL,'NIR',NULL,NULL),
            ('400','KF Vllaznia',NULL,'ALB',NULL,NULL),
            ('401','KS Luftëtari',NULL,'ALB',NULL,NULL),
            ('402','FC Ararat',NULL,'ARM',NULL,NULL),
            ('403','FC Shirak',NULL,'ARM',NULL,NULL),
            ('404','RoPS Rovaniemi',NULL,'FIN',NULL,NULL),
            ('405','FC Gandzasar',NULL,'ARM',NULL,NULL),
            ('406','FC Lahti',NULL,'FIN',NULL,NULL),
            ('407','IFK Mariehamn',NULL,'FIN',NULL,NULL),
            ('408','VPS Vaasa',NULL,'FIN',NULL,NULL),
            ('409','SJK Seinäjoki',NULL,'FIN',NULL,NULL),
            ('410','KF Renova',NULL,'MKD',NULL,NULL),
            ('411','FK Rabotnicki',NULL,'MKD',NULL,NULL),
            ('412','FC Gagra',NULL,'GEO',NULL,NULL),
            ('413','FC Struga',NULL,'MKD',NULL,NULL),
            ('414','Mosta FC',NULL,'MLT',NULL,NULL),
            ('415','FC Dila Gori',NULL,'MLT',NULL,NULL),
            ('416','FC Sirens',NULL,'MLT',NULL,NULL),
            ('417','FK Makedonija GP Skopje',NULL,'MKD',NULL,NULL),
            ('418','Akademija Pandev',NULL,'MKD',NULL,NULL),
            ('419','FK Pelister',NULL,'MKD',NULL,NULL),
            ('420','Newtown AFC',NULL,'WAL',NULL,NULL),
            ('421','Barry Town AFC',NULL,'WAL',NULL,NULL),
            ('422','Cardiff Metropolitan University FC',NULL,'WAL',NULL,NULL),
            ('423','Cefn Druids AFC',NULL,'WAL',NULL,NULL),
            ('424','Bangor City FC',NULL,'WAL',NULL,NULL),
            ('425','Víkingur Reykjavík',NULL,'ISL',NULL,NULL),
            ('426','ÍBV Vestmannaeyjar',NULL,'ISL',NULL,NULL),
            ('427','FCI Tallinn',NULL,'EST',NULL,NULL),
            ('428','Mons Calpe SC',NULL,'GIB',NULL,NULL),
            ('429','FK Dečić',NULL,'MNE',NULL,NULL),
            ('430','FK Podgorica',NULL,'MNE',NULL,NULL),
            ('431','FK Iskra',NULL,'MNE',NULL,NULL),
            ('432','FK Rudar Pljevlja',NULL,'MNE',NULL,NULL),
            ('433','UE Santa Coloma',NULL,'AND',NULL,NULL)");
    }
}